### ISSUE TITLE
[BUG] cannot hotplug when the "old" pod does not have network-selection-elements

### ISSUE THREAD

**Issue by maiqueb** [maiqueb/multus-dynamic-networks-controller#43]
**Describe the bug**
It currently is impossible to hotplug interfaces into a pod that does **not** feature any network selection elements - `k8s.v1.cni.cncf.io/networks`.

**Expected behavior**
It should be possible to hotplug interfaces into a pod without network-selection-elements.

**To Reproduce**
1. Provision the following pod: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tiny-winy-pod
  name: tiny-winy-pod
spec:
  containers:
  - command:
    - /bin/ash
    - -c
    - 'trap : TERM INT; sleep infinity & wait'
    image: k8s.gcr.io/e2e-test-images/agnhost:2.26
    imagePullPolicy: IfNotPresent
    name: samplepod
```
2. Hot-plug an interface into it - add the following annotation:
```yaml
k8s.v1.cni.cncf.io/networks: '[{"name":"tenant-network","namespace":"ns1","mac":"02:03:04:05:06:07","interface":"ens58"}]'
```
3. It'll fail to add the interface, and the network-status will not feature this new attachment.
