### ISSUE TITLE
[BUG] the net-attach-def used for hotplug should not require the `name` attribute

### ISSUE THREAD

**Issue by maiqueb** [maiqueb/multus-dynamic-networks-controller#45]
**Describe the bug**
According to the [multi-net spec](https://github.com/k8snetworkplumbingwg/multi-net-spec/blob/master/v1.1/%5Bv1.1%5D%20Kubernetes%20Network%20Custom%20Resource%20Definition%20De-facto%20Standard.pdf) - section 3.4.2 - the `name` attribute of the net-attach-def `.Spec.Config` attribute could be inferred from the metadata attribute.

This currently is a required attribute.

**Expected behavior**
Infer the spec.config.name attribute from the metadata.name.

**To Reproduce**
1. provision a net-attach-def without a name attribute in its `spec.config`
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan1-config
spec:
  config: '{
            "cniVersion": "0.4.0",
            "plugins": [
                {
                    "type": "macvlan",
                    "master": "eth1",
                    "mode": "bridge",
                }
            ]
        }'
```
2. attempt to hotplug an interface into a running pod which uses the aforementioned net-attach-def
3. it will fail with the following error:
```
ERRORED: error configuring pod [default/virt-launcher-vmi-a-cccsh] networking: missing network name:
```

**Environment**:
- multus-dynamic-networks-controller version: N/A
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- OS (e.g. from /etc/os-release): N/A
- Controller configuration (`criSocketPath` / `multusSocketPath`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.
